// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7IIFZsXkOihW3T6ofByJINu0qnrZJqiI',
    appId: '1:47324457736:web:bcf9331147be25d8c95abd',
    messagingSenderId: '47324457736',
    projectId: 'followup-dcf46',
    authDomain: 'followup-dcf46.firebaseapp.com',
    storageBucket: 'followup-dcf46.appspot.com',
    measurementId: 'G-ZR8GE8W9NC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfPt1lHFfk-uPtw6UdP_uu8iRkYJmdH94',
    appId: '1:47324457736:android:85e182e30f8842bcc95abd',
    messagingSenderId: '47324457736',
    projectId: 'followup-dcf46',
    storageBucket: 'followup-dcf46.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdWej8aK1YRwgzcjEPyv1Ke7Vvoheyc_U',
    appId: '1:47324457736:ios:27ef678968eefb30c95abd',
    messagingSenderId: '47324457736',
    projectId: 'followup-dcf46',
    storageBucket: 'followup-dcf46.appspot.com',
    iosBundleId: 'com.example.followup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdWej8aK1YRwgzcjEPyv1Ke7Vvoheyc_U',
    appId: '1:47324457736:ios:af3ec077a9edc849c95abd',
    messagingSenderId: '47324457736',
    projectId: 'followup-dcf46',
    storageBucket: 'followup-dcf46.appspot.com',
    iosBundleId: 'com.example.followup.RunnerTests',
  );
}
